packages:
  - "apps/*"
  - "packages/*"

catalogs:
  dev:
    react: "19.2.7"
    react-dom: "19.2.7"
    "@types/react": "19.2.17"
    "@types/react-dom": "19.2.3"
  peer:
    react: "^19.0.0"
    react-dom: "^19.0.0"

engineStrict: true
