name: QA

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Build packages
        run: pnpm build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run tests
        run: pnpm test

  oxlint:
    name: Oxlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run Oxlint
        run: pnpm lint

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run typecheck
        run: pnpm typecheck

  oxfmt:
    name: Oxfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run Oxfmt
        run: pnpm format:check
